# Generated by Django 4.0.6 on 2022-07-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('apples', models.FloatField()),
                ('bananas', models.FloatField()),
            ],
        ),
    ]
